@startuml
actor User
participant ":Parser" as P
participant ":AddCommand" as AC
participant ":ApplicationList" as AL
participant ":Storage" as S

User -> P : parse("add c/Google r/SWE")
P --> AC : create

AC -> AL : hasApplication(...)
AL --> AC : false
AC -> AL : addApplication(...)
AC --> User : confirmation message
AC -> S : save(...)
@enduml
