@startuml
actor User
participant ":Parser" as P
participant ":ArchiveCommand" as AC
participant ":ApplicationList" as AL
participant "app:Application" as app
participant ":Storage" as S

User -> P : parse("archive 1")
P --> AC : create

AC -> AL : getActiveApplication(1)
AL --> AC : app
AC -> app : setArchived(true)
AC -> S : save(...)
AC --> User : confirmation message
@enduml
