@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 10

participant ":InternTrackr" as IT
participant "c:FilterCommand" as FC
participant ":ApplicationList" as AL
participant "app:Application" as App
participant ":Ui" as UI

[-> IT : executeCommand()
activate IT

IT -> FC : execute(applications, ui, storage)
activate FC

ref over FC, AL : Validation and Normalization of Status

loop for each application in ApplicationList
    FC -> AL : getApplication(i)
    activate AL
    AL --> FC : app
    deactivate AL

    opt app matches filter criteria AND is not archived
        FC -> UI : showMessage(app.toString())
        activate UI
        UI --> FC
        deactivate UI
    end
end

deactivate FC
[<-- IT
deactivate IT
@enduml
