@startuml
participant ":InternTrackr" as IT
participant "c:FindCommand" as FC
participant ":ApplicationList" as AL
participant ":Ui" as UI

[-> IT : executeCommand()
activate IT

IT -> FC : execute(applications, ui, storage)
activate FC

FC -> AL : getApplications()
activate AL
AL --> FC : list
deactivate AL

note right of FC : Filters list based on keyword\n(Case-insensitive)

alt matches found
    FC -> UI : showMessage(matchingResults)
    activate UI
    UI --> FC
    deactivate UI
else no matches
    FC -> UI : showMessage("No matching applications found.")
    activate UI
    UI --> FC
    deactivate UI
end

deactivate FC
[<-- IT
deactivate IT
@enduml
