@startuml
actor User
participant ":InternTrackr" as IT
participant "c:ClearCommand" as CC
participant ":Ui" as UI
participant ":ApplicationList" as AL
participant ":Storage" as ST

User -> IT : "clear"
activate IT
IT -> CC : execute(applications, ui, storage)
activate CC

CC -> UI : showMessage("Are you sure...")
activate UI
UI --> CC
deactivate UI

CC -> UI : readCommand()
activate UI
UI --> CC : "yes"
deactivate UI

opt response.equalsIgnoreCase("yes")
    CC -> AL : clear()
    activate AL
    AL --> CC
    deactivate AL

    CC -> AL : getApplications()
    activate AL
    AL --> CC : list
    deactivate AL

    CC -> ST : save(list)
    activate ST
    ST --> CC
    deactivate ST

    CC -> UI : showMessage("All data has been cleared.")
    activate UI
    UI --> CC
    deactivate UI
end

deactivate CC
IT --> User
deactivate IT
@enduml
