@startuml
participant ":InternTrackr" as IT
participant ":Ui" as UI
participant ":Parser" as P

IT -> UI : readCommand()
UI --> IT : fullCommand
IT -> UI : showLine()
IT -> P : parse(fullCommand)
P --> IT : throws InternTrackrException
IT -> UI : showError(message)
IT -> UI : showLine()
note right of IT : loop continues;\nno crash
@enduml
