@startuml
actor User
participant ":InternTrackr" as IT
participant ":Ui" as UI
participant ":Parser" as P
participant "c:HelpCommand" as HC

IT -> UI : readCommand()
activate UI
User -> UI : types "help"
UI --> IT : "help"
deactivate UI

IT -> P : parse("help")
activate P
P --> IT : c (HelpCommand)
deactivate P

IT -> HC : execute(applications, ui, storage)
activate HC

HC -> UI : showMessage(User Guide URL)
activate UI
UI --> HC
deactivate UI

HC --> IT
deactivate HC

IT -> UI : showLine()
activate UI
UI -> User : displays output
deactivate UI
@enduml
